-- Tam sayı sütunlarında kalmış ondalık değerleri onarır.
--
-- Bu sütunlar bulutta integer/bigint. Yerelde SQLite ondalığı sessizce
-- kabul ediyordu: vardiya sonunda "238,5" yazılan kilometre cihazda
-- real olarak durdu, gönderimde Postgres reddetti ve tablo tek istekte
-- gittiği için o tablonun bütün yedeği takıldı. Yazma yolları artık
-- tam sayı yazıyor; burada daha önce yazılmış olanlar düzeltiliyor.
--
-- SQLite ROUND sıfırdan uzağa yarım yuvarlıyor (2,5 → 3), para ile aynı
-- kural. updated_at BİR ARTAR: bu sürüm buluta hiç ulaşamadı, onarılan
-- satır yeni bir düzeltme gibi gitmeli.
--
-- SIRA ÖNEMLİ: önce kuyruk, sonra onarım — onarımdan sonra hangi satırın
-- ondalık olduğu artık görülemez. Takılmış kuyruk kaydının denemesi de
-- sıfırlanır; bekleme süresi dolmadan yeniden gitsin.
INSERT INTO `outbox` (`table_name`, `row_id`, `user_id`, `operation`, `revision`, `attempt_count`, `created_at`)
SELECT 'app_settings', `id`, `user_id`, CASE WHEN `deleted_at` IS NULL THEN 'upsert' ELSE 'delete' END, 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000
FROM `app_settings` WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`day_cutoff_hour`) = 'real' OR typeof(`onboarding_completed_at`) = 'real'
ON CONFLICT (`table_name`, `row_id`) DO UPDATE SET `operation` = excluded.`operation`, `user_id` = excluded.`user_id`, `revision` = `outbox`.`revision` + 1, `attempt_count` = 0, `last_error` = NULL, `next_attempt_at` = NULL;
--> statement-breakpoint
UPDATE `app_settings` SET `created_at` = CASE WHEN typeof(`created_at`) = 'real' THEN CAST(ROUND(`created_at`) AS INTEGER) ELSE `created_at` END, `deleted_at` = CASE WHEN typeof(`deleted_at`) = 'real' THEN CAST(ROUND(`deleted_at`) AS INTEGER) ELSE `deleted_at` END, `day_cutoff_hour` = CASE WHEN typeof(`day_cutoff_hour`) = 'real' THEN CAST(ROUND(`day_cutoff_hour`) AS INTEGER) ELSE `day_cutoff_hour` END, `onboarding_completed_at` = CASE WHEN typeof(`onboarding_completed_at`) = 'real' THEN CAST(ROUND(`onboarding_completed_at`) AS INTEGER) ELSE `onboarding_completed_at` END, `updated_at` = CAST(ROUND(`updated_at`) AS INTEGER) + 1
WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`day_cutoff_hour`) = 'real' OR typeof(`onboarding_completed_at`) = 'real';
--> statement-breakpoint
INSERT INTO `outbox` (`table_name`, `row_id`, `user_id`, `operation`, `revision`, `attempt_count`, `created_at`)
SELECT 'vehicles', `id`, `user_id`, CASE WHEN `deleted_at` IS NULL THEN 'upsert' ELSE 'delete' END, 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000
FROM `vehicles` WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`model_year`) = 'real' OR typeof(`initial_odometer_km`) = 'real' OR typeof(`wear_per_km_kurus`) = 'real' OR typeof(`sort_order`) = 'real'
ON CONFLICT (`table_name`, `row_id`) DO UPDATE SET `operation` = excluded.`operation`, `user_id` = excluded.`user_id`, `revision` = `outbox`.`revision` + 1, `attempt_count` = 0, `last_error` = NULL, `next_attempt_at` = NULL;
--> statement-breakpoint
UPDATE `vehicles` SET `created_at` = CASE WHEN typeof(`created_at`) = 'real' THEN CAST(ROUND(`created_at`) AS INTEGER) ELSE `created_at` END, `deleted_at` = CASE WHEN typeof(`deleted_at`) = 'real' THEN CAST(ROUND(`deleted_at`) AS INTEGER) ELSE `deleted_at` END, `model_year` = CASE WHEN typeof(`model_year`) = 'real' THEN CAST(ROUND(`model_year`) AS INTEGER) ELSE `model_year` END, `initial_odometer_km` = CASE WHEN typeof(`initial_odometer_km`) = 'real' THEN CAST(ROUND(`initial_odometer_km`) AS INTEGER) ELSE `initial_odometer_km` END, `wear_per_km_kurus` = CASE WHEN typeof(`wear_per_km_kurus`) = 'real' THEN CAST(ROUND(`wear_per_km_kurus`) AS INTEGER) ELSE `wear_per_km_kurus` END, `sort_order` = CASE WHEN typeof(`sort_order`) = 'real' THEN CAST(ROUND(`sort_order`) AS INTEGER) ELSE `sort_order` END, `updated_at` = CAST(ROUND(`updated_at`) AS INTEGER) + 1
WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`model_year`) = 'real' OR typeof(`initial_odometer_km`) = 'real' OR typeof(`wear_per_km_kurus`) = 'real' OR typeof(`sort_order`) = 'real';
--> statement-breakpoint
INSERT INTO `outbox` (`table_name`, `row_id`, `user_id`, `operation`, `revision`, `attempt_count`, `created_at`)
SELECT 'vehicle_fuel_types', `id`, `user_id`, CASE WHEN `deleted_at` IS NULL THEN 'upsert' ELSE 'delete' END, 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000
FROM `vehicle_fuel_types` WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`avg_consumption_per_100km`) = 'real' OR typeof(`last_unit_price_kurus`) = 'real'
ON CONFLICT (`table_name`, `row_id`) DO UPDATE SET `operation` = excluded.`operation`, `user_id` = excluded.`user_id`, `revision` = `outbox`.`revision` + 1, `attempt_count` = 0, `last_error` = NULL, `next_attempt_at` = NULL;
--> statement-breakpoint
UPDATE `vehicle_fuel_types` SET `created_at` = CASE WHEN typeof(`created_at`) = 'real' THEN CAST(ROUND(`created_at`) AS INTEGER) ELSE `created_at` END, `deleted_at` = CASE WHEN typeof(`deleted_at`) = 'real' THEN CAST(ROUND(`deleted_at`) AS INTEGER) ELSE `deleted_at` END, `avg_consumption_per_100km` = CASE WHEN typeof(`avg_consumption_per_100km`) = 'real' THEN CAST(ROUND(`avg_consumption_per_100km`) AS INTEGER) ELSE `avg_consumption_per_100km` END, `last_unit_price_kurus` = CASE WHEN typeof(`last_unit_price_kurus`) = 'real' THEN CAST(ROUND(`last_unit_price_kurus`) AS INTEGER) ELSE `last_unit_price_kurus` END, `updated_at` = CAST(ROUND(`updated_at`) AS INTEGER) + 1
WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`avg_consumption_per_100km`) = 'real' OR typeof(`last_unit_price_kurus`) = 'real';
--> statement-breakpoint
INSERT INTO `outbox` (`table_name`, `row_id`, `user_id`, `operation`, `revision`, `attempt_count`, `created_at`)
SELECT 'earning_sources', `id`, `user_id`, CASE WHEN `deleted_at` IS NULL THEN 'upsert' ELSE 'delete' END, 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000
FROM `earning_sources` WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`default_commission_bps`) = 'real' OR typeof(`sort_order`) = 'real'
ON CONFLICT (`table_name`, `row_id`) DO UPDATE SET `operation` = excluded.`operation`, `user_id` = excluded.`user_id`, `revision` = `outbox`.`revision` + 1, `attempt_count` = 0, `last_error` = NULL, `next_attempt_at` = NULL;
--> statement-breakpoint
UPDATE `earning_sources` SET `created_at` = CASE WHEN typeof(`created_at`) = 'real' THEN CAST(ROUND(`created_at`) AS INTEGER) ELSE `created_at` END, `deleted_at` = CASE WHEN typeof(`deleted_at`) = 'real' THEN CAST(ROUND(`deleted_at`) AS INTEGER) ELSE `deleted_at` END, `default_commission_bps` = CASE WHEN typeof(`default_commission_bps`) = 'real' THEN CAST(ROUND(`default_commission_bps`) AS INTEGER) ELSE `default_commission_bps` END, `sort_order` = CASE WHEN typeof(`sort_order`) = 'real' THEN CAST(ROUND(`sort_order`) AS INTEGER) ELSE `sort_order` END, `updated_at` = CAST(ROUND(`updated_at`) AS INTEGER) + 1
WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`default_commission_bps`) = 'real' OR typeof(`sort_order`) = 'real';
--> statement-breakpoint
INSERT INTO `outbox` (`table_name`, `row_id`, `user_id`, `operation`, `revision`, `attempt_count`, `created_at`)
SELECT 'expense_categories', `id`, `user_id`, CASE WHEN `deleted_at` IS NULL THEN 'upsert' ELSE 'delete' END, 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000
FROM `expense_categories` WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`sort_order`) = 'real'
ON CONFLICT (`table_name`, `row_id`) DO UPDATE SET `operation` = excluded.`operation`, `user_id` = excluded.`user_id`, `revision` = `outbox`.`revision` + 1, `attempt_count` = 0, `last_error` = NULL, `next_attempt_at` = NULL;
--> statement-breakpoint
UPDATE `expense_categories` SET `created_at` = CASE WHEN typeof(`created_at`) = 'real' THEN CAST(ROUND(`created_at`) AS INTEGER) ELSE `created_at` END, `deleted_at` = CASE WHEN typeof(`deleted_at`) = 'real' THEN CAST(ROUND(`deleted_at`) AS INTEGER) ELSE `deleted_at` END, `sort_order` = CASE WHEN typeof(`sort_order`) = 'real' THEN CAST(ROUND(`sort_order`) AS INTEGER) ELSE `sort_order` END, `updated_at` = CAST(ROUND(`updated_at`) AS INTEGER) + 1
WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`sort_order`) = 'real';
--> statement-breakpoint
INSERT INTO `outbox` (`table_name`, `row_id`, `user_id`, `operation`, `revision`, `attempt_count`, `created_at`)
SELECT 'shifts', `id`, `user_id`, CASE WHEN `deleted_at` IS NULL THEN 'upsert' ELSE 'delete' END, 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000
FROM `shifts` WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`started_at`) = 'real' OR typeof(`ended_at`) = 'real' OR typeof(`start_odometer_km`) = 'real' OR typeof(`end_odometer_km`) = 'real' OR typeof(`distance_km`) = 'real' OR typeof(`worked_minutes`) = 'real' OR typeof(`commission_kurus`) = 'real' OR typeof(`fuel_consumption_per_100km`) = 'real' OR typeof(`fuel_price_kurus`) = 'real'
ON CONFLICT (`table_name`, `row_id`) DO UPDATE SET `operation` = excluded.`operation`, `user_id` = excluded.`user_id`, `revision` = `outbox`.`revision` + 1, `attempt_count` = 0, `last_error` = NULL, `next_attempt_at` = NULL;
--> statement-breakpoint
UPDATE `shifts` SET `created_at` = CASE WHEN typeof(`created_at`) = 'real' THEN CAST(ROUND(`created_at`) AS INTEGER) ELSE `created_at` END, `deleted_at` = CASE WHEN typeof(`deleted_at`) = 'real' THEN CAST(ROUND(`deleted_at`) AS INTEGER) ELSE `deleted_at` END, `started_at` = CASE WHEN typeof(`started_at`) = 'real' THEN CAST(ROUND(`started_at`) AS INTEGER) ELSE `started_at` END, `ended_at` = CASE WHEN typeof(`ended_at`) = 'real' THEN CAST(ROUND(`ended_at`) AS INTEGER) ELSE `ended_at` END, `start_odometer_km` = CASE WHEN typeof(`start_odometer_km`) = 'real' THEN CAST(ROUND(`start_odometer_km`) AS INTEGER) ELSE `start_odometer_km` END, `end_odometer_km` = CASE WHEN typeof(`end_odometer_km`) = 'real' THEN CAST(ROUND(`end_odometer_km`) AS INTEGER) ELSE `end_odometer_km` END, `distance_km` = CASE WHEN typeof(`distance_km`) = 'real' THEN CAST(ROUND(`distance_km`) AS INTEGER) ELSE `distance_km` END, `worked_minutes` = CASE WHEN typeof(`worked_minutes`) = 'real' THEN CAST(ROUND(`worked_minutes`) AS INTEGER) ELSE `worked_minutes` END, `commission_kurus` = CASE WHEN typeof(`commission_kurus`) = 'real' THEN CAST(ROUND(`commission_kurus`) AS INTEGER) ELSE `commission_kurus` END, `fuel_consumption_per_100km` = CASE WHEN typeof(`fuel_consumption_per_100km`) = 'real' THEN CAST(ROUND(`fuel_consumption_per_100km`) AS INTEGER) ELSE `fuel_consumption_per_100km` END, `fuel_price_kurus` = CASE WHEN typeof(`fuel_price_kurus`) = 'real' THEN CAST(ROUND(`fuel_price_kurus`) AS INTEGER) ELSE `fuel_price_kurus` END, `updated_at` = CAST(ROUND(`updated_at`) AS INTEGER) + 1
WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`started_at`) = 'real' OR typeof(`ended_at`) = 'real' OR typeof(`start_odometer_km`) = 'real' OR typeof(`end_odometer_km`) = 'real' OR typeof(`distance_km`) = 'real' OR typeof(`worked_minutes`) = 'real' OR typeof(`commission_kurus`) = 'real' OR typeof(`fuel_consumption_per_100km`) = 'real' OR typeof(`fuel_price_kurus`) = 'real';
--> statement-breakpoint
INSERT INTO `outbox` (`table_name`, `row_id`, `user_id`, `operation`, `revision`, `attempt_count`, `created_at`)
SELECT 'rides', `id`, `user_id`, CASE WHEN `deleted_at` IS NULL THEN 'upsert' ELSE 'delete' END, 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000
FROM `rides` WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`occurred_at`) = 'real' OR typeof(`gross_amount_kurus`) = 'real' OR typeof(`commission_kurus`) = 'real' OR typeof(`net_amount_kurus`) = 'real' OR typeof(`commission_bps`) = 'real' OR typeof(`tip_kurus`) = 'real' OR typeof(`distance_meters`) = 'real' OR typeof(`duration_seconds`) = 'real'
ON CONFLICT (`table_name`, `row_id`) DO UPDATE SET `operation` = excluded.`operation`, `user_id` = excluded.`user_id`, `revision` = `outbox`.`revision` + 1, `attempt_count` = 0, `last_error` = NULL, `next_attempt_at` = NULL;
--> statement-breakpoint
UPDATE `rides` SET `created_at` = CASE WHEN typeof(`created_at`) = 'real' THEN CAST(ROUND(`created_at`) AS INTEGER) ELSE `created_at` END, `deleted_at` = CASE WHEN typeof(`deleted_at`) = 'real' THEN CAST(ROUND(`deleted_at`) AS INTEGER) ELSE `deleted_at` END, `occurred_at` = CASE WHEN typeof(`occurred_at`) = 'real' THEN CAST(ROUND(`occurred_at`) AS INTEGER) ELSE `occurred_at` END, `gross_amount_kurus` = CASE WHEN typeof(`gross_amount_kurus`) = 'real' THEN CAST(ROUND(`gross_amount_kurus`) AS INTEGER) ELSE `gross_amount_kurus` END, `commission_kurus` = CASE WHEN typeof(`commission_kurus`) = 'real' THEN CAST(ROUND(`commission_kurus`) AS INTEGER) ELSE `commission_kurus` END, `net_amount_kurus` = CASE WHEN typeof(`net_amount_kurus`) = 'real' THEN CAST(ROUND(`net_amount_kurus`) AS INTEGER) ELSE `net_amount_kurus` END, `commission_bps` = CASE WHEN typeof(`commission_bps`) = 'real' THEN CAST(ROUND(`commission_bps`) AS INTEGER) ELSE `commission_bps` END, `tip_kurus` = CASE WHEN typeof(`tip_kurus`) = 'real' THEN CAST(ROUND(`tip_kurus`) AS INTEGER) ELSE `tip_kurus` END, `distance_meters` = CASE WHEN typeof(`distance_meters`) = 'real' THEN CAST(ROUND(`distance_meters`) AS INTEGER) ELSE `distance_meters` END, `duration_seconds` = CASE WHEN typeof(`duration_seconds`) = 'real' THEN CAST(ROUND(`duration_seconds`) AS INTEGER) ELSE `duration_seconds` END, `updated_at` = CAST(ROUND(`updated_at`) AS INTEGER) + 1
WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`occurred_at`) = 'real' OR typeof(`gross_amount_kurus`) = 'real' OR typeof(`commission_kurus`) = 'real' OR typeof(`net_amount_kurus`) = 'real' OR typeof(`commission_bps`) = 'real' OR typeof(`tip_kurus`) = 'real' OR typeof(`distance_meters`) = 'real' OR typeof(`duration_seconds`) = 'real';
--> statement-breakpoint
INSERT INTO `outbox` (`table_name`, `row_id`, `user_id`, `operation`, `revision`, `attempt_count`, `created_at`)
SELECT 'expenses', `id`, `user_id`, CASE WHEN `deleted_at` IS NULL THEN 'upsert' ELSE 'delete' END, 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000
FROM `expenses` WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`amount_kurus`) = 'real' OR typeof(`occurred_at`) = 'real'
ON CONFLICT (`table_name`, `row_id`) DO UPDATE SET `operation` = excluded.`operation`, `user_id` = excluded.`user_id`, `revision` = `outbox`.`revision` + 1, `attempt_count` = 0, `last_error` = NULL, `next_attempt_at` = NULL;
--> statement-breakpoint
UPDATE `expenses` SET `created_at` = CASE WHEN typeof(`created_at`) = 'real' THEN CAST(ROUND(`created_at`) AS INTEGER) ELSE `created_at` END, `deleted_at` = CASE WHEN typeof(`deleted_at`) = 'real' THEN CAST(ROUND(`deleted_at`) AS INTEGER) ELSE `deleted_at` END, `amount_kurus` = CASE WHEN typeof(`amount_kurus`) = 'real' THEN CAST(ROUND(`amount_kurus`) AS INTEGER) ELSE `amount_kurus` END, `occurred_at` = CASE WHEN typeof(`occurred_at`) = 'real' THEN CAST(ROUND(`occurred_at`) AS INTEGER) ELSE `occurred_at` END, `updated_at` = CAST(ROUND(`updated_at`) AS INTEGER) + 1
WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`amount_kurus`) = 'real' OR typeof(`occurred_at`) = 'real';
--> statement-breakpoint
INSERT INTO `outbox` (`table_name`, `row_id`, `user_id`, `operation`, `revision`, `attempt_count`, `created_at`)
SELECT 'recurring_expenses', `id`, `user_id`, CASE WHEN `deleted_at` IS NULL THEN 'upsert' ELSE 'delete' END, 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000
FROM `recurring_expenses` WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`amount_kurus`) = 'real'
ON CONFLICT (`table_name`, `row_id`) DO UPDATE SET `operation` = excluded.`operation`, `user_id` = excluded.`user_id`, `revision` = `outbox`.`revision` + 1, `attempt_count` = 0, `last_error` = NULL, `next_attempt_at` = NULL;
--> statement-breakpoint
UPDATE `recurring_expenses` SET `created_at` = CASE WHEN typeof(`created_at`) = 'real' THEN CAST(ROUND(`created_at`) AS INTEGER) ELSE `created_at` END, `deleted_at` = CASE WHEN typeof(`deleted_at`) = 'real' THEN CAST(ROUND(`deleted_at`) AS INTEGER) ELSE `deleted_at` END, `amount_kurus` = CASE WHEN typeof(`amount_kurus`) = 'real' THEN CAST(ROUND(`amount_kurus`) AS INTEGER) ELSE `amount_kurus` END, `updated_at` = CAST(ROUND(`updated_at`) AS INTEGER) + 1
WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`amount_kurus`) = 'real';
--> statement-breakpoint
INSERT INTO `outbox` (`table_name`, `row_id`, `user_id`, `operation`, `revision`, `attempt_count`, `created_at`)
SELECT 'fuel_logs', `id`, `user_id`, CASE WHEN `deleted_at` IS NULL THEN 'upsert' ELSE 'delete' END, 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000
FROM `fuel_logs` WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`occurred_at`) = 'real' OR typeof(`volume_per1000`) = 'real' OR typeof(`unit_price_kurus`) = 'real' OR typeof(`total_amount_kurus`) = 'real' OR typeof(`odometer_km`) = 'real'
ON CONFLICT (`table_name`, `row_id`) DO UPDATE SET `operation` = excluded.`operation`, `user_id` = excluded.`user_id`, `revision` = `outbox`.`revision` + 1, `attempt_count` = 0, `last_error` = NULL, `next_attempt_at` = NULL;
--> statement-breakpoint
UPDATE `fuel_logs` SET `created_at` = CASE WHEN typeof(`created_at`) = 'real' THEN CAST(ROUND(`created_at`) AS INTEGER) ELSE `created_at` END, `deleted_at` = CASE WHEN typeof(`deleted_at`) = 'real' THEN CAST(ROUND(`deleted_at`) AS INTEGER) ELSE `deleted_at` END, `occurred_at` = CASE WHEN typeof(`occurred_at`) = 'real' THEN CAST(ROUND(`occurred_at`) AS INTEGER) ELSE `occurred_at` END, `volume_per1000` = CASE WHEN typeof(`volume_per1000`) = 'real' THEN CAST(ROUND(`volume_per1000`) AS INTEGER) ELSE `volume_per1000` END, `unit_price_kurus` = CASE WHEN typeof(`unit_price_kurus`) = 'real' THEN CAST(ROUND(`unit_price_kurus`) AS INTEGER) ELSE `unit_price_kurus` END, `total_amount_kurus` = CASE WHEN typeof(`total_amount_kurus`) = 'real' THEN CAST(ROUND(`total_amount_kurus`) AS INTEGER) ELSE `total_amount_kurus` END, `odometer_km` = CASE WHEN typeof(`odometer_km`) = 'real' THEN CAST(ROUND(`odometer_km`) AS INTEGER) ELSE `odometer_km` END, `updated_at` = CAST(ROUND(`updated_at`) AS INTEGER) + 1
WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`occurred_at`) = 'real' OR typeof(`volume_per1000`) = 'real' OR typeof(`unit_price_kurus`) = 'real' OR typeof(`total_amount_kurus`) = 'real' OR typeof(`odometer_km`) = 'real';
--> statement-breakpoint
INSERT INTO `outbox` (`table_name`, `row_id`, `user_id`, `operation`, `revision`, `attempt_count`, `created_at`)
SELECT 'goals', `id`, `user_id`, CASE WHEN `deleted_at` IS NULL THEN 'upsert' ELSE 'delete' END, 1, 0, CAST(strftime('%s', 'now') AS INTEGER) * 1000
FROM `goals` WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`target_net_kurus`) = 'real'
ON CONFLICT (`table_name`, `row_id`) DO UPDATE SET `operation` = excluded.`operation`, `user_id` = excluded.`user_id`, `revision` = `outbox`.`revision` + 1, `attempt_count` = 0, `last_error` = NULL, `next_attempt_at` = NULL;
--> statement-breakpoint
UPDATE `goals` SET `created_at` = CASE WHEN typeof(`created_at`) = 'real' THEN CAST(ROUND(`created_at`) AS INTEGER) ELSE `created_at` END, `deleted_at` = CASE WHEN typeof(`deleted_at`) = 'real' THEN CAST(ROUND(`deleted_at`) AS INTEGER) ELSE `deleted_at` END, `target_net_kurus` = CASE WHEN typeof(`target_net_kurus`) = 'real' THEN CAST(ROUND(`target_net_kurus`) AS INTEGER) ELSE `target_net_kurus` END, `updated_at` = CAST(ROUND(`updated_at`) AS INTEGER) + 1
WHERE typeof(`created_at`) = 'real' OR typeof(`updated_at`) = 'real' OR typeof(`deleted_at`) = 'real' OR typeof(`target_net_kurus`) = 'real';
